name: CI Pipeline

on:
  push:
    branches:
      - master  # Adjust this to your default branch
  pull_request:
    branches:
      - master  # Adjust this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug Secrets
      run: |
        echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"
        echo "Docker Password: ${{ secrets.DOCKER_PASSWORD }}"  # Only for debugging; remove after testing

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: docker build -t ayesha2004/your-docker-image-name .

    - name: Push the Docker image
      run: docker push ayesha2004/your-docker-image-name
