name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # or your main branch name
  pull_request:
    branches:
      - master  # or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t ayesha2004/react-app .

    - name: Push Docker image
      run: docker push ayesha2004/react-app
